### ISSUE TITLE
Readability algorithm

### ISSUE THREAD

**Issue by Anonyfox** [Anonyfox/elixir-scrape#16]
Currently, fetching the full text from a HTML article is more or less a dirty hack to get the keywords/tags going. https://github.com/keepcosmos/readability seems to be a straight port from arc90's readability algorithm, could deliver better results while also increasing the computation demand.

**Comment by Anonyfox** [comment]
waiting for https://github.com/keepcosmos/readability/issues/8 for now.

**Comment by noma4i** [comment]
Correspondent issue is resolved now.

**Comment by Anonyfox** [comment]
added readability in v3
