### ISSUE TITLE
New hex release?

### ISSUE THREAD

**Issue by dotdotdotpaul** [Anonyfox/elixir-scrape#23]
I can see that the timex dependency was updated to 3.0 two months ago, but if you're using hex to pull the package with "~> 1.2", we're still getting a version that's dependent on a 2.x version of timex.  Is there something blocking the hex package update I can help with?

**Comment by edevil** [comment]
Any news on this? I'm also getting dependency resolution problems because of the old timex dependency.

**Comment by Anonyfox** [comment]
@edevil  @dotdotdotpaul 

I'll have a look at it this weekend and release the current master then. Are the current dependencies all up to date? If you want a special version, just send a PR. :)
