### ISSUE TITLE
Is this project abandonned ?

### ISSUE THREAD

**Issue by julienmarie** [Anonyfox/elixir-scrape#38]
Should someone take over ?

**Comment by Anonyfox** [comment]
Basically I don‘t do elixir any more (moved everything to serverless/fullstack/javascript), and only merge pull requests. If someone wants ts fork and maintain things, i‘d set up a redirect message to the fork.

**Comment by RaphSfeir** [comment]
As mentioned on my pull request, I'm actively using and working this repository, so I'd be happy to help. #39

**Comment by Anonyfox** [comment]
merged, thanks!

**Comment by Anonyfox** [comment]
rewrite done in version v3. needs some polish still, but a good working state is published now
