### ISSUE TITLE
Go forward with html5ever?

### ISSUE THREAD

**Issue by Anonyfox** [Anonyfox/elixir-scrape#42]
Question for all users of this lib: Do you prefer the current (fast) usage of html5ever or would you like to return to a pure Elixir implementation?

**Comment by esconsut1** [comment]
pure Elixir implementation.
Because so many issues with rust and dependencies in development -- not to mention when deploying on slightly difference production environments -- even with docker.

**Comment by Anonyfox** [comment]
reverted to pure elixir in v3
